apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pyxis-compute
spec:
  selector:
    matchLabels:
      app: pyxis-compute
  template:
    metadata:
      labels:
        app: pyxis-compute
    spec:
      containers:
        - name: compute-server
          image: shengqipku/pyxis-compute:latest
          command:
            - /pyxis/compute
            - --workers=${WORKERS}
          env:
            - name: WORKERS
              value: "8"
      nodeSelector:
        node-restriction.kubernetes.io/placement_label: compute-server
      restartPolicy: Always
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pyxis-storage
spec:
  selector:
    matchLabels:
      app: pyxis-storage
  template:
    metadata:
      labels:
        app: pyxis-storage
    spec:
      containers:
        - name: storage-server
          image: shengqipku/pyxis-storage:latest
          command:
            - /pyxis/storage
            - --workers=${WORKERS}
          env:
            - name: WORKERS
              value: "4"
      nodeSelector:
        node-restriction.kubernetes.io/placement_label: storage-server
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: pyxis-compute
spec:
  selector:
    app: pyxis-compute
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: pyxis-storage
spec:
  selector:
    app: pyxis-storage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: ClusterIP
